export enum Notifications {
    REQUISITION_FINISHED,
    PUBLISHER_FINISHED,
    SUBSCRIPTION_FINISHED,
    HOOK_FINISHED,

    REQUISITION_STARTED,
    PUBLISHER_STARTED,
    SUBSCRIPTION_STARTED,
}
