files:
  - examples/*.yml
  - examples/*.json

parallel: true

log-level: warn

max-report-level-print: 3

outputs:
  - type: file
    format: json
    filename: output/examples.json
  - type: file
    format: yml #default
    filename: output/examples.yml
  # - type: standard-output
  #   format: console

#plugins:
#-   enqueuer-plugin-amqp

store:
  tcpPayload: enqueuer Rocks

  skipped: 5

  privateKey: |-
    -----BEGIN PRIVATE KEY-----
    MIIJQwIBADANBgkqhkiG9w0BAQEFAASCCS0wggkpAgEAAoICAQCvS13lL5sOsrZ8
    pNKIOPWzs077+dmuafQBSosXyC8aUh6eNvGbDjc/KcL42ri1YgkrITZfdwt7lOh0
    /R4gge7QslakuARpFa6uS9VcHTocj/YYqDLKEzutxhZR5DLv77YP9HEXXy6BoUNH
    XZJBhEF/PsUzeQdiywtF3oMvcyJd0ubxsheZTk+1MBS5xECMkWh92vwtby6lnXC8
    VGUEWLCypSx8clqZM84NT48rEqczW2YSeIsfu3OslEutzMtzEiw++jqHh5MzLwXQ
    c9KGpCXEQv6OkabKMQXRQqHopUT7tELesClOTPeQdb9CFjHgZZEYCnmlx33rIIFG
    7s3Y2Idy8S2O3LUDr+ITg65wlqqRUz8adPtlSrUHWBZxWsVG1pMAwrZY8SAgy1UT
    RGGCrqLf7qx2yA+F1941r+QUWfTH/glO7EQV0kVJuJQk6gqyFatJa6IxoJwk1HAv
    e26+hSRNYj82Hon8BcQTvo0tIrXy8vc/eoEuY0zu07hJaZyE09UfuuajZdaDvOHB
    sCQ2gysakTBNN3cosLOndgOCC3f9odmrZn0MBAn8WJcq18G+gqspVSdgbVsbjsIj
    J9EDov24uECrHsPg/I9HYdx02tGyTUYGXCPBZ3DF1+OWkg0oTlqqLl2iiPBBCu9a
    3YL4RAskr4JyNOc0wE1T+nTkzGmwdwIDAQABAoICAArX6KkCtt7D41H2iCdxDpHd
    J6einvqRB00FJXGFKpTAO7ChyXRD/trjZHIsZXyi4dpPJaPmI0mzvmVuOuzb3MAA
    KCfsUimF89ZITpxyGmQl650+2lVxtyFavYq3SQdalrKJ9mzxsFjIdvb1LNTsr3iF
    k4FJnVFZKgtaZlcLEjcnkq2kzJzpITkeDkonf66yV/phD3RoCkSoZo7f0ZfhPJzw
    Zr4T/NK5R6e/IiYR81HT945w8no2CEPGsJ/BqVwm5aHHrNMxacOixwNMBtvZT5TC
    aCi9jcm4GpoFOyq+/nNrhS9tSkDTtgSzo+8cnF07KyyHiVrd6kYfLqAKqaUeT9KM
    Lxd88UU8XnMkDvvta20uql23qu3AxqXDVoRcdtimgrtxeRTETRoyQhDoOZ07p/fn
    SqUQ2+uUYDGY+0qIMLkUJjRSGdUvcb2xwLsaiokzMDL1WwO9PzXLb4xQ4bQtVcNa
    dLhVXlzyXl9+ipCEN82K3hlS3XtPz0mWb6HGk7nz6lago03PmIXjj3G+H95jAUeF
    dGku/jx6qG3qtCJdFvimHTSJMa31EW+aAj0bMlRGo5shtnVazgiHPYFx4Rc5dEC4
    CmuhQieJdPp4rna/k00ESIjIOUEfB3uQLLAaGCSKQ7yjQFWeJ7+Y8MbwUlgGiBbn
    GzR/ZNf21BERpeEsFOfBAoIBAQDV8+ZeiVzG+g+Zkko/DTl/y7As2JjOEaoffaSj
    RZxQe/UiZNiVa3O2MBjcq3VnulzeLSXAIrI4lR3UZSivevbUtccmtFKxROuNBphE
    QJdiVjvm5+c5S+75N2Di94IPjKKE2JKhR2Y/Te1dlAXnrKSv5Zay4MQvhMHCwb1v
    Qdjq7ZiVZ6DS+acnhAxSt3A4nVwpbpORcebJH320Il0y4lsaH67vJytxcn5zoAri
    vOsszA724v/2dtYTrzDq0rykgdlQKF4kxICZiY4jpSINXFRAJjTTI8vbr9msiKI1
    bzmGF6oME8/fgbWqCJmj2KpwW6AV/zR8OJFK8RZ4HC3n3grxAoIBAQDRvoqPC9B7
    zqkz27197D1MV/wmgCrZD5CfwyCkGWxNCy01L+RL7VnlAm0QB4ve5D7pcAMjZSh5
    SPf084WGp7VSSoii8nGWhgrY7dvBF4ocMe77swXPEWBALFHJ+N/RyqWsRH03X/3s
    I/DFoG1mttmmO7QV4PDAT3ne/+EWbFHB/LYRCmlSLbkW3EzR5Lj5nqJSSnZe8/0E
    cWVMCwGoomg9WROt4Zz1I+O5Jqrq0xk94gWy6R/ZD8JOXQnEma1CNgVGzrEFwbG+
    zmkxhw02J2fttIbY0OR6ab3XOhmyGmto5Djnf/LWDdFtwoQHcfRa0GPwpj/092zL
    HNi+Zy/CcOHnAoIBAQCeqPg1MvgyNk5LPEkC6POy6YIEP7tRVZgrMildSsnYhZQL
    pW1XoQ92E8TcH+o4ueMUf7Z2/UPc4ff1Ae9h8nYI16SP9zk7bDihpDpWou+gZQKX
    AXJe8wiMl5yps5Inpcr/aPuTzjbsywUzWAno/AZEyqUuka/q7TAjFTk9wD70OK3m
    XarNyYVDsJDS5mW6Fje6Id4dBbJ3g3rckn86tNGKVeSMRSfaQWW0qQJpkl90IP8X
    5s6aHxYyEsDb4tsxw3k8EDOAYJhdQ7y8gkD2V3nC+JJD4U/T4lwxrkFcDtdBsVrR
    CgAlZzMonKgS8SGzoL7ekRqC5BAa2x4mg/8m62qBAoIBAAeEidjYto9Jd/0Y2jDi
    P8w1tx72JxMCoM9pIglfs+cLCILIhalHB5rSvG//pT7G9Y5Oan5hSNMYD3MjK10J
    M9GQRFd60yFvCoJ9/AtuuY+LJqK05vdmCwohzIitt/AAEHIdPlO2yBYnr6CVwHYX
    BbQUnb7PAjISZy7cAwhXt5J5aVkxA1djtiegm8xGI28nBXBnpNiAbEg1fEj+d//A
    WnYgdDkeRg7vS2E+ho/GIzh5mnSwMGkKTI+cfBYk3/Xok8XW8LdhGurY4SJaUdno
    DaySdObejeHpWlmVhohAtCrdS0DY8C5F7oS9nRfbOMPshjiA7PftymN5VDd24VpZ
    y28CggEBAL2gs8CZCVx73oqa8orfkBKsJtcI2u26AjeX4SJO9iKd0hOryajNOTEd
    1mReBWLLJ3Az4PaQMpdUGXDub3E4XvlJsMnCAfN+YHY3sWzcmepML19V0uzQ7duj
    rYGJDxUB+5pI/xF5MKmg6852mXCkaqbbgBLhUmtSI263pgogJJD3qqwYA5q2BtUk
    1hgKYX2VDdfQ6ddF+a/IOgUebDl2Sqmjz+ZOkkne3OQ48Dfpw90rchfJ0qg8jwvH
    9ZSUK3GFSY7pgN6io9js5B2+UBbOLGIp9SC3cTg/Eo9zEKVhcMvtiV1xSMwAGJ2z
    jJbWxM6E9pAcqPiVGvMJ/RdmPk6rqjs=
    -----END PRIVATE KEY-----

  certificate: |-
    -----BEGIN CERTIFICATE-----
    MIIFxTCCA62gAwIBAgIUbGsuXsC9D4FiukBFNWQLbsG0jJ8wDQYJKoZIhvcNAQEL
    BQAwcjELMAkGA1UEBhMCQ0ExGTAXBgNVBAgMEEJyaXRpc2ggQ29sdW1iaWExEjAQ
    BgNVBAcMCVZhbmNvdXZlcjEUMBIGA1UECgwLVmlyZ3VsYXRpb24xDjAMBgNVBAsM
    BVZpcmdzMQ4wDAYDVQQDDAVWaXJnczAeFw0yNDA4MTkyMTU0MzFaFw0zNDA4MTcy
    MTU0MzFaMHIxCzAJBgNVBAYTAkNBMRkwFwYDVQQIDBBCcml0aXNoIENvbHVtYmlh
    MRIwEAYDVQQHDAlWYW5jb3V2ZXIxFDASBgNVBAoMC1Zpcmd1bGF0aW9uMQ4wDAYD
    VQQLDAVWaXJnczEOMAwGA1UEAwwFVmlyZ3MwggIiMA0GCSqGSIb3DQEBAQUAA4IC
    DwAwggIKAoICAQCvS13lL5sOsrZ8pNKIOPWzs077+dmuafQBSosXyC8aUh6eNvGb
    Djc/KcL42ri1YgkrITZfdwt7lOh0/R4gge7QslakuARpFa6uS9VcHTocj/YYqDLK
    EzutxhZR5DLv77YP9HEXXy6BoUNHXZJBhEF/PsUzeQdiywtF3oMvcyJd0ubxsheZ
    Tk+1MBS5xECMkWh92vwtby6lnXC8VGUEWLCypSx8clqZM84NT48rEqczW2YSeIsf
    u3OslEutzMtzEiw++jqHh5MzLwXQc9KGpCXEQv6OkabKMQXRQqHopUT7tELesClO
    TPeQdb9CFjHgZZEYCnmlx33rIIFG7s3Y2Idy8S2O3LUDr+ITg65wlqqRUz8adPtl
    SrUHWBZxWsVG1pMAwrZY8SAgy1UTRGGCrqLf7qx2yA+F1941r+QUWfTH/glO7EQV
    0kVJuJQk6gqyFatJa6IxoJwk1HAve26+hSRNYj82Hon8BcQTvo0tIrXy8vc/eoEu
    Y0zu07hJaZyE09UfuuajZdaDvOHBsCQ2gysakTBNN3cosLOndgOCC3f9odmrZn0M
    BAn8WJcq18G+gqspVSdgbVsbjsIjJ9EDov24uECrHsPg/I9HYdx02tGyTUYGXCPB
    Z3DF1+OWkg0oTlqqLl2iiPBBCu9a3YL4RAskr4JyNOc0wE1T+nTkzGmwdwIDAQAB
    o1MwUTAdBgNVHQ4EFgQUQxL+b147fKJnrFqpqBpH6aowMnMwHwYDVR0jBBgwFoAU
    QxL+b147fKJnrFqpqBpH6aowMnMwDwYDVR0TAQH/BAUwAwEB/zANBgkqhkiG9w0B
    AQsFAAOCAgEAgM3sjsSiJVpNjoIYokRoJFQmv1ZcYmZ4x01CzQQu98wdNFq0Uhlk
    0h9EvbBzqlQ0Uu57ylTwsRepl8B08r1oAW93EAxweRPWo6enC+FalVLh9HWcpKGU
    sDCfZfwyFugrTCtSJd+qiYB9PMp/xmjvZyT1k4h2ZFYmjJWEC1T1+nx+g3hxUH8H
    KxLG5KyfdFmQ5FD9Wx9lT0pPaDrRZYjsU7JEgp3uM1egY9wRJYSWI8euhFodnEIB
    zvdzhSoPXPcyVhrtJeNocnHhB17/dkD6oU/9nUGdfUjPBnBYWSJDZ+IR5yicjO0a
    pyPFlNYYXgDFqpn2ocinw/VREAZnjhlLyPVs3sGhCzApQleyUqUGcR03D367N/nf
    OdUO3QyQramWAhxZwyD1p1V9ouozR1jCyLRQ4NdpQDRw8T8VJ0ZHBj9pIvc8uNey
    pkMEysrWuCEmO5QMGPsOz6Nc0WsdxefNfUfOBddQSWqSN89umBV9LWTMU8Ss8yra
    jb4mSiiWJBzCzFHVPpgNIsBDmJpcmg1vG3jS941AXftjJTHTMrL+hIM9TWRd2kEk
    jkpvXwhjCP53LlmQudR+wwf8tcuRJ5+3Hdl03amAdMmRfQKseZdpDitY9jtZUuE2
    oo/64xDCrMTqa1k+hgRPu6+4Q8s4pdZAqHUqIceYkBveONk/2Ly5nNc=
    -----END CERTIFICATE-----
