export enum ChildReceivingEvents {
    RUN_REQUISITION = 'RUN_REQUISITION',
    ADD_MODULE = 'ADD_MODULE',
    GET_PROTOCOLS = 'GET_PROTOCOLS',
    GET_ASSERTERS = 'GET_ASSERTERS',
    CLEAN_STORE = 'CLEAN_STORE',
}
