export enum ChildReceivingEvents {
  SET_STORE = 'SET_STORE',
  ADD_MODULE = 'ADD_MODULE',
  CLEAN_STORE = 'CLEAN_STORE',
  GET_PROTOCOLS = 'GET_PROTOCOLS',
  GET_ASSERTERS = 'GET_ASSERTERS',
  RUN_REQUISITION = 'RUN_REQUISITION'
}
